language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -v ./...

# deploy:
#   provider: heroku
#   api_key: 058fbbcd-83db-41ed-b87a-de0700eec45b
#   app: hergo2